# Generated by Django 3.2.5 on 2021-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('author', models.TextField(max_length=400)),
                ('publication_date', models.DateField(null=True)),
                ('isbn', models.TextField(max_length=20)),
                ('pages', models.IntegerField(null=True)),
                ('link', models.TextField(max_length=400, null=True)),
                ('language', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
